### ISSUE TITLE
gravity-spring-plugin is missed

### ISSUE THREAD

**Issue by leehyoo-io** [tangyiming/sql-detect#2]
当我对sql-capture-plugin项目进行打包的时候，找不到包
com.tangym:sql-capture-plugin:jar:0.0.1-SNAPSHOT: Could not find artifact com.tangym:gravity-spring-plugin:jar:0.0.1-SNAPSHOT

**Comment by tangyiming** [comment]
那就把项目里的gravity-spring-plugin通过maven先install一下到本地
