### ISSUE TITLE
跑项目报错：gravity-agent.jar中没有主清单属性

### ISSUE THREAD

**Issue by zoujiegogogo** [tangyiming/sql-detect#3]
![image](https://user-images.githubusercontent.com/48706279/209277387-13448aa7-ccc6-48fc-b518-24516f3e06e1.png)
运行环境是JDK17

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/209279126-842e94d9-2d4f-440d-841b-061ab6af2072.png)
最后我用的是1.8的环境构建的，运行起来也是跑不起来

**Comment by tangyiming** [comment]
这是java agent 不是fat jar，你那样运行不对，具体如何搞，请认真看下readme
